import type { Category, Product } from "./types";

export const categories: Category[] = [
  { id: "all", name: "Semua", icon: "🛒" },
  { id: "fruits-veg", name: "Buah & Sayur", icon: "🥦" },
  { id: "dairy-eggs", name: "Susu & Telur", icon: "🥛" },
  { id: "snacks", name: "Snack", icon: "🍿" },
  { id: "beverages", name: "Minuman", icon: "🥤" },
  { id: "bakery", name: "Roti & Kue", icon: "🍞" },
  { id: "staples", name: "Sembako", icon: "🍚" },
  { id: "household", name: "Kebutuhan Rumah", icon: "🧻" },
  { id: "personal-care", name: "Perawatan Diri", icon: "🧴" },
];

export const products: Product[] = [
  // Fruits & Vegetables
  {
    id: "p-apple",
    name: "Apel Fuji",
    categoryId: "fruits-veg",
    price: 32000,
    unit: "500 g",
    image: "🍎",
    description: "Apel Fuji segar, manis, dan renyah. Kaya serat dan vitamin C.",
    stock: 40,
    discountPercent: 10,
  },
  {
    id: "p-banana",
    name: "Pisang Cavendish",
    categoryId: "fruits-veg",
    price: 24000,
    unit: "1 sisir",
    image: "🍌",
    description: "Pisang Cavendish matang sempurna, sumber energi dan kalium.",
    stock: 55,
  },
  {
    id: "p-tomato",
    name: "Tomat Segar",
    categoryId: "fruits-veg",
    price: 15000,
    unit: "500 g",
    image: "🍅",
    description: "Tomat merah segar untuk masakan sehari-hari.",
    stock: 60,
  },
  {
    id: "p-broccoli",
    name: "Brokoli",
    categoryId: "fruits-veg",
    price: 18000,
    unit: "250 g",
    image: "🥦",
    description: "Brokoli hijau segar, kaya nutrisi dan serat.",
    stock: 30,
  },
  {
    id: "p-carrot",
    name: "Wortel",
    categoryId: "fruits-veg",
    price: 12000,
    unit: "500 g",
    image: "🥕",
    description: "Wortel manis segar, bagus untuk mata dan camilan sehat.",
    stock: 48,
  },

  // Dairy & Eggs
  {
    id: "p-milk",
    name: "Susu UHT Full Cream",
    categoryId: "dairy-eggs",
    price: 19000,
    unit: "1 L",
    image: "🥛",
    description: "Susu UHT full cream, sumber kalsium dan protein.",
    stock: 70,
  },
  {
    id: "p-eggs",
    name: "Telur Ayam Negeri",
    categoryId: "dairy-eggs",
    price: 28000,
    unit: "10 butir",
    image: "🥚",
    description: "Telur ayam segar berkualitas, sumber protein terbaik.",
    stock: 65,
    discountPercent: 5,
  },
  {
    id: "p-cheese",
    name: "Keju Cheddar",
    categoryId: "dairy-eggs",
    price: 34000,
    unit: "170 g",
    image: "🧀",
    description: "Keju cheddar gurih untuk roti, pasta, dan masakan.",
    stock: 25,
  },
  {
    id: "p-butter",
    name: "Mentega",
    categoryId: "dairy-eggs",
    price: 22000,
    unit: "200 g",
    image: "🧈",
    description: "Mentega lembut untuk memasak dan memanggang.",
    stock: 20,
  },

  // Snacks
  {
    id: "p-chips",
    name: "Keripik Kentang",
    categoryId: "snacks",
    price: 16000,
    unit: "68 g",
    image: "🍟",
    description: "Keripik kentang renyah dengan rasa gurih.",
    stock: 90,
  },
  {
    id: "p-cookies",
    name: "Biskuit Cokelat",
    categoryId: "snacks",
    price: 14000,
    unit: "120 g",
    image: "🍪",
    description: "Biskuit dengan cokelat chip yang lumer.",
    stock: 80,
    discountPercent: 15,
  },
  {
    id: "p-popcorn",
    name: "Popcorn Karamel",
    categoryId: "snacks",
    price: 20000,
    unit: "100 g",
    image: "🍿",
    description: "Popcorn karamel manis untuk teman nonton.",
    stock: 45,
  },

  // Beverages
  {
    id: "p-water",
    name: "Air Mineral",
    categoryId: "beverages",
    price: 6000,
    unit: "600 ml",
    image: "💧",
    description: "Air mineral segar untuk hidrasi sehari-hari.",
    stock: 120,
  },
  {
    id: "p-coffee",
    name: "Kopi Susu Botol",
    categoryId: "beverages",
    price: 18000,
    unit: "250 ml",
    image: "☕",
    description: "Kopi susu siap minum, pas untuk penambah semangat.",
    stock: 60,
  },
  {
    id: "p-juice",
    name: "Jus Jeruk",
    categoryId: "beverages",
    price: 21000,
    unit: "1 L",
    image: "🧃",
    description: "Jus jeruk segar tanpa pengawet, kaya vitamin C.",
    stock: 40,
    discountPercent: 10,
  },
  {
    id: "p-tea",
    name: "Teh Melati",
    categoryId: "beverages",
    price: 9000,
    unit: "500 ml",
    image: "🍵",
    description: "Teh melati wangi menyegarkan.",
    stock: 75,
  },

  // Bakery
  {
    id: "p-bread",
    name: "Roti Tawar Gandum",
    categoryId: "bakery",
    price: 17000,
    unit: "1 pack",
    image: "🍞",
    description: "Roti tawar gandum lembut, cocok untuk sarapan.",
    stock: 35,
  },
  {
    id: "p-croissant",
    name: "Croissant Butter",
    categoryId: "bakery",
    price: 15000,
    unit: "1 pcs",
    image: "🥐",
    description: "Croissant renyah dengan aroma butter yang khas.",
    stock: 28,
  },
  {
    id: "p-donut",
    name: "Donat Cokelat",
    categoryId: "bakery",
    price: 12000,
    unit: "1 pcs",
    image: "🍩",
    description: "Donat empuk dengan topping cokelat.",
    stock: 50,
  },

  // Staples
  {
    id: "p-rice",
    name: "Beras Premium",
    categoryId: "staples",
    price: 68000,
    unit: "5 kg",
    image: "🍚",
    description: "Beras premium pulen dan wangi.",
    stock: 40,
    discountPercent: 8,
  },
  {
    id: "p-oil",
    name: "Minyak Goreng",
    categoryId: "staples",
    price: 38000,
    unit: "2 L",
    image: "🛢️",
    description: "Minyak goreng berkualitas untuk masakan.",
    stock: 55,
  },
  {
    id: "p-sugar",
    name: "Gula Pasir",
    categoryId: "staples",
    price: 16000,
    unit: "1 kg",
    image: "🧂",
    description: "Gula pasir putih bersih.",
    stock: 60,
  },
  {
    id: "p-noodle",
    name: "Mie Instan",
    categoryId: "staples",
    price: 3500,
    unit: "1 pcs",
    image: "🍜",
    description: "Mie instan favorit, cepat dan praktis.",
    stock: 200,
  },

  // Household
  {
    id: "p-tissue",
    name: "Tisu Gulung",
    categoryId: "household",
    price: 25000,
    unit: "4 roll",
    image: "🧻",
    description: "Tisu gulung lembut dan kuat.",
    stock: 70,
  },
  {
    id: "p-detergent",
    name: "Deterjen Cair",
    categoryId: "household",
    price: 32000,
    unit: "800 ml",
    image: "🧴",
    description: "Deterjen cair untuk cucian bersih maksimal.",
    stock: 40,
    discountPercent: 12,
  },
  {
    id: "p-dishsoap",
    name: "Sabun Cuci Piring",
    categoryId: "household",
    price: 14000,
    unit: "780 ml",
    image: "🧽",
    description: "Sabun cuci piring dengan busa melimpah.",
    stock: 50,
  },

  // Personal Care
  {
    id: "p-shampoo",
    name: "Sampo",
    categoryId: "personal-care",
    price: 29000,
    unit: "170 ml",
    image: "🧴",
    description: "Sampo lembut untuk rambut sehat berkilau.",
    stock: 45,
  },
  {
    id: "p-toothpaste",
    name: "Pasta Gigi",
    categoryId: "personal-care",
    price: 13000,
    unit: "190 g",
    image: "🪥",
    description: "Pasta gigi untuk gigi kuat dan napas segar.",
    stock: 65,
  },
  {
    id: "p-soap",
    name: "Sabun Mandi",
    categoryId: "personal-care",
    price: 9000,
    unit: "1 pcs",
    image: "🧼",
    description: "Sabun mandi wangi menyegarkan.",
    stock: 80,
  },
];

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}
